name: Terraform-Plan

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main
    paths:
    - 'src/terraform/**'

env:
  TERRAFORM_VERSION: '1.5.7'
  WORKING_DIRECTORY: "./src/terraform"
  APPLICATION_NAME: fleet-ops
  ENVIRONMENT_NAME: dev

jobs:

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: setup
      name: Setup `terraform`
      uses: hashicorp/setup-terraform@main
      with:
        version: ${{ env.TERRAFORM_VERSION }}

    - id: plan
      name: Terraform Plan
      env:
        ARM_SUBSCRIPTION_ID: "0cfe2870-d256-4119-b0a3-16293ac11bdc"
        ARM_TENANT_ID: "84f1e4ea-8554-43e1-8709-f0b8589ea118"
        ARM_CLIENT_ID: "3dae92aa-1117-4a99-a58a-50885506f3ea"
        ARM_CLIENT_SECRET: ${{ secrets.PACKER_ARM_CLIENT_SECRET }}
        BACKEND_RESOURCE_GROUP_NAME: "1-ba067086-playground-sandbox"
        BACKEND_STORAGE_ACCOUNT_NAME: "sitaramdemo"
        BACKEND_STORAGE_CONTAINER_NAME: "demo"
        TF_BACKEND_KEY: ${{ env.APPLICATION_NAME }}-${{ env.ENVIRONMENT_NAME }}
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        terraform init \
          -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
          -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$BACKEND_STORAGE_CONTAINER_NAME" \
          -backend-config="key=$TF_BACKEND_KEY"
          
        terraform plan
